### ISSUE TITLE
ハンバーガーメニューの作成

### ISSUE THREAD

**Issue by kurakke** [kurakke/nitkit-shot#7]
右上にある三本線のハンバーガーメニューの作成をしてもらいます
コンポーネント化した上で、ページ遷移が正常に行えることの確認までをタスクの範囲とします
予約用LINEbotへのリンクは環境変数でURLを定義しましょう
レスポンシブの対応は必要です
https://www.figma.com/file/MrXV11oN1AFcHkgHLXQOFO/R5-4I-Web-%E3%83%87%E3%82%B6%E3%82%A4%E3%83%B3?type=design&node-id=1-3&mode=design&t=jkcJy2X3Efv5CsJu-0

**Comment by kai02221514** [comment]
環境変数に定義する予約用LINEbotへのURLをどう定義すればいいのかわからないので、参考記事などはありますか？

**Comment by kurakke** [comment]
この記事を参考にすると良いと思います
https://dev.classmethod.jp/articles/tips-when-using-environment-variables-on-the-client-side-with-nextjs/

**Comment by kurakke** [comment]
以下のPRで解決されたので、このIssueを閉じます
https://github.com/kurakke/nitkit-shot/pull/18
