### ISSUE TITLE
使用するフォントの定義

### ISSUE THREAD

**Issue by kurakke** [kurakke/nitkit-shot#8]
今回使用するフォントをfigmaを元に確認した上で導入します
デザインの方と相談しながら進めることになると思うので、コミュニケーションを円滑にするよう心がけましょう
TailwindConfに定義してutilsにも定義し、表示の確認をするところまでがこのIssueの達成目標です
PRを出すときはフォントが正しく使用出来ているかのチェックの意味も込めてスクショを説明のところに貼ってください
https://www.figma.com/file/MrXV11oN1AFcHkgHLXQOFO/R5-4I-Web-%E3%83%87%E3%82%B6%E3%82%A4%E3%83%B3?type=design&node-id=1-3&mode=design&t=jkcJy2X3Efv5CsJu-0

**Comment by kai02221514** [comment]
「utilsへの定義」がよくわからないので具体例を挙げていただけると助かります。

**Comment by kurakke** [comment]
Utilsに定義してImportする形にしようかなって思ったけど、ちゃんと調べたら管理大変そうだしメリット多くなかったので、普通にTailwindConfに定義してもらってOKです

**Comment by kai02221514** [comment]
了解です。

**Comment by kurakke** [comment]
こちらのPRで完了したためIssueを閉じます
https://github.com/kurakke/nitkit-shot/pull/15
